In [2]:
import pandas as pd

In [8]:
import os

os.listdir("../data")

[]

In [12]:
df = pd.read_excel("../data/sample_-_superstore.xls")

In [14]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [16]:
df.shape

(10194, 21)

In [18]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [22]:
df.duplicated().sum()

np.int64(0)

In [24]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [26]:
(df['Profit'] < 0).sum()

np.int64(1901)

In [28]:
(df['Profit'] < 0).mean() * 100

np.float64(18.648224445752405)

In [30]:
df['Sales'].sum()

np.float64(2326534.3543)

In [32]:
df['Profit'].sum()

np.float64(292296.8145999999)

In [34]:
(df['Profit'].sum() / df['Sales'].sum()) * 100

np.float64(12.563614805849074)

In [36]:
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

Region
West       739813.6085
East       691828.1680
Central    503170.6728
South      391721.9050
Name: Sales, dtype: float64

In [38]:
df.groupby('Region')['Profit'].sum().sort_values(ascending=False)

Region
West       110798.8170
East        94883.2603
South       46749.4303
Central     39865.3070
Name: Profit, dtype: float64

In [40]:
df.groupby('Region')[['Sales', 'Profit']].sum().sort_values('Sales', ascending=False)

               Sales       Profit
Region
West     739813.6085  110798.8170
East     691828.1680   94883.2603
Central  503170.6728   39865.3070
South    391721.9050   46749.4303

In [42]:
region_summary = df.groupby('Region')[['Sales', 'Profit']].sum()

region_summary['Profit Margin %'] = (
    region_summary['Profit'] / region_summary['Sales']
) * 100

region_summary.sort_values('Profit Margin %', ascending=False)

               Sales       Profit  Profit Margin %
Region
West     739813.6085  110798.8170        14.976585
East     691828.1680   94883.2603        13.714859
South    391721.9050   46749.4303        11.934342
Central  503170.6728   39865.3070         7.922820

In [44]:
df.groupby('Region')['Discount'].mean().sort_values(ascending=False)

Region
Central    0.241002
South      0.147253
East       0.143436
West       0.108946
Name: Discount, dtype: float64

In [46]:
df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

Category
Technology         146543.3756
Office Supplies    126023.4434
Furniture           19729.9956
Name: Profit, dtype: float64

In [48]:
df.groupby('Category')[['Sales', 'Profit']].sum().sort_values('Sales', ascending=False)

                       Sales       Profit
Category
Technology       839893.2790  146543.3756
Furniture        754747.7613   19729.9956
Office Supplies  731893.3140  126023.4434

In [50]:
category_summary = df.groupby('Category')[['Sales', 'Profit']].sum()

category_summary['Profit Margin %'] = (
    category_summary['Profit'] / category_summary['Sales']
) * 100

category_summary.sort_values('Profit Margin %', ascending=False)

                       Sales       Profit  Profit Margin %
Category
Technology       839893.2790  146543.3756        17.447857
Office Supplies  731893.3140  126023.4434        17.218827
Furniture        754747.7613   19729.9956         2.614118

In [52]:
df[df['Category'] == 'Furniture'].groupby('Sub-Category')['Profit'].sum().sort_values()

Sub-Category
Tables        -17753.2061
Bookcases      -3632.0736
Furnishings    13891.7430
Chairs         27223.5323
Name: Profit, dtype: float64

In [54]:
df[df['Category'] == 'Furniture'].groupby('Sub-Category')['Discount'].mean().sort_values(ascending=False)

Sub-Category
Tables         0.258129
Bookcases      0.215259
Chairs         0.169243
Furnishings    0.138057
Name: Discount, dtype: float64

In [56]:
df[df['Category'] == 'Furniture'].groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)

Sub-Category
Chairs         335768.2490
Tables         208020.1820
Bookcases      115361.2043
Furnishings     95598.1260
Name: Sales, dtype: float64

In [58]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[^a-zA-Z0-9]+', '_', regex=True)
    .str.strip('_')
)

In [60]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country_region', 'city',
       'state_province', 'postal_code', 'region', 'product_id', 'category',
       'sub_category', 'product_name', 'sales', 'quantity', 'discount',
       'profit'],
      dtype='object')

In [62]:
df.to_csv("../data/superstore_cleaned.csv", index=False)

In [64]:
import sqlite3

In [66]:
conn = sqlite3.connect("../data/superstore.db")

In [68]:
df.to_sql("sales", conn, if_exists="replace", index=False)

10194

In [70]:
query = """
SELECT *
FROM sales
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country_region,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,US-2023-103800,2023-01-03 00:00:00,2023-01-07 00:00:00,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04 00:00:00,2023-01-08 00:00:00,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04 00:00:00,2023-01-08 00:00:00,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04 00:00:00,2023-01-08 00:00:00,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05 00:00:00,2023-01-12 00:00:00,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [72]:
query = """
SELECT SUM(sales) AS total_sales
FROM sales;
"""

pd.read_sql_query(query, conn)

    total_sales
0  2.326534e+06

In [74]:
query = """
SELECT SUM(profit) AS total_profit
FROM sales;
"""

pd.read_sql_query(query, conn)

   total_profit
0   292296.8146

In [76]:
query = """
SELECT 
    (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
FROM sales;
"""

pd.read_sql_query(query, conn)

   profit_margin_percent
0              12.563615

In [78]:
query = """
SELECT 
    region,
    SUM(sales) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC;
"""

pd.read_sql_query(query, conn)

    region  total_sales
0     West  739813.6085
1     East  691828.1680
2  Central  503170.6728
3    South  391721.9050

In [80]:
query = """
SELECT 
    region,
    SUM(profit) AS total_profit
FROM sales
GROUP BY region
ORDER BY total_profit DESC;
"""

pd.read_sql_query(query, conn)

    region  total_profit
0     West   110798.8170
1     East    94883.2603
2    South    46749.4303
3  Central    39865.3070

In [81]:
query = """
SELECT 
    region,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
FROM sales
GROUP BY region
ORDER BY profit_margin_percent DESC;
"""

pd.read_sql_query(query, conn)

    region  total_sales  total_profit  profit_margin_percent
0     West  739813.6085   110798.8170              14.976585
1     East  691828.1680    94883.2603              13.714859
2    South  391721.9050    46749.4303              11.934342
3  Central  503170.6728    39865.3070               7.922820