In [79]:
import pandas as pd
import sqlite3

In [80]:
conn = sqlite3.connect("../data/superstore.db")

In [81]:
query = """
SELECT *
FROM sales
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country_region,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,US-2023-103800,2023-01-03 00:00:00,2023-01-07 00:00:00,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04 00:00:00,2023-01-08 00:00:00,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04 00:00:00,2023-01-08 00:00:00,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04 00:00:00,2023-01-08 00:00:00,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05 00:00:00,2023-01-12 00:00:00,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [82]:
def run_query(sql):
    return pd.read_sql_query(sql, conn)

In [83]:
run_query("""
SELECT 
    region,
    SUM(sales) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC;
""")

    region  total_sales
0     West  739813.6085
1     East  691828.1680
2  Central  503170.6728
3    South  391721.9050

In [84]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [85]:
simple_copilot("show me sales by region")

    region  total_sales
0     West  739813.6085
1     East  691828.1680
2  Central  503170.6728
3    South  391721.9050

In [86]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [87]:
simple_copilot("show me profit by region")

    region  total_profit
0     West   110798.8170
1     East    94883.2603
2    South    46749.4303
3  Central    39865.3070

In [88]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [89]:
simple_copilot("what are the total sales")

    total_sales
0  2.326534e+06

In [90]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    elif "total profit" in question:
        return run_query("""
        SELECT 
            SUM(profit) AS total_profit
        FROM sales;
        """)

    elif "profit margin" in question:
        return run_query("""
        SELECT 
            (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
        FROM sales;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [91]:
simple_copilot("what is the profit margin")

   profit_margin_percent
0              12.563615

In [92]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    elif "total profit" in question:
        return run_query("""
        SELECT 
            SUM(profit) AS total_profit
        FROM sales;
        """)

    elif "profit margin" in question:
        return run_query("""
        SELECT 
            (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
        FROM sales;
        """)

    elif "sales by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY category
        ORDER BY total_sales DESC;
        """)

    elif "profit by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY category
        ORDER BY total_profit DESC;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [93]:
simple_copilot("show me profit by category")

          category  total_profit
0       Technology   146543.3756
1  Office Supplies   126023.4434
2        Furniture    19729.9956

In [94]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    elif "total profit" in question:
        return run_query("""
        SELECT 
            SUM(profit) AS total_profit
        FROM sales;
        """)

    elif "profit margin" in question:
        return run_query("""
        SELECT 
            (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
        FROM sales;
        """)

    elif "sales by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY category
        ORDER BY total_sales DESC;
        """)

    elif "profit by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY category
        ORDER BY total_profit DESC;
        """)

    elif "top customers" in question:
        return run_query("""
        SELECT 
            customer_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY customer_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [95]:
simple_copilot("show me the top customers")

        customer_name  total_sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

In [96]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    elif "total profit" in question:
        return run_query("""
        SELECT 
            SUM(profit) AS total_profit
        FROM sales;
        """)

    elif "profit margin" in question:
        return run_query("""
        SELECT 
            (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
        FROM sales;
        """)

    elif "sales by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY category
        ORDER BY total_sales DESC;
        """)

    elif "profit by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY category
        ORDER BY total_profit DESC;
        """)

    elif "top customers" in question:
        return run_query("""
        SELECT 
            customer_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY customer_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    elif "top products" in question:
        return run_query("""
        SELECT 
            product_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY product_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [97]:
simple_copilot("show me the top products")

                                        product_name  total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

In [98]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    elif "total profit" in question:
        return run_query("""
        SELECT 
            SUM(profit) AS total_profit
        FROM sales;
        """)

    elif "profit margin" in question:
        return run_query("""
        SELECT 
            (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
        FROM sales;
        """)

    elif "sales by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY category
        ORDER BY total_sales DESC;
        """)

    elif "profit by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY category
        ORDER BY total_profit DESC;
        """)

    elif "top customers" in question:
        return run_query("""
        SELECT 
            customer_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY customer_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    elif "top products" in question:
        return run_query("""
        SELECT 
            product_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY product_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    elif "sales by segment" in question:
        return run_query("""
        SELECT 
            segment,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY segment
        ORDER BY total_sales DESC;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [99]:
simple_copilot("show me sales by segment")

       segment   total_sales
0     Consumer  1.170660e+06
1    Corporate  7.158061e+05
2  Home Office  4.400684e+05

In [100]:
def simple_copilot(question):
    question = question.lower()

    if "sales by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY region
        ORDER BY total_sales DESC;
        """)

    elif "profit by region" in question:
        return run_query("""
        SELECT 
            region,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY region
        ORDER BY total_profit DESC;
        """)

    elif "total sales" in question:
        return run_query("""
        SELECT 
            SUM(sales) AS total_sales
        FROM sales;
        """)

    elif "total profit" in question:
        return run_query("""
        SELECT 
            SUM(profit) AS total_profit
        FROM sales;
        """)

    elif "profit margin" in question:
        return run_query("""
        SELECT 
            (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
        FROM sales;
        """)

    elif "sales by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY category
        ORDER BY total_sales DESC;
        """)

    elif "profit by category" in question:
        return run_query("""
        SELECT 
            category,
            SUM(profit) AS total_profit
        FROM sales
        GROUP BY category
        ORDER BY total_profit DESC;
        """)

    elif "top customers" in question:
        return run_query("""
        SELECT 
            customer_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY customer_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    elif "top products" in question:
        return run_query("""
        SELECT 
            product_name,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY product_name
        ORDER BY total_sales DESC
        LIMIT 10;
        """)

    elif "sales by segment" in question:
        return run_query("""
        SELECT 
            segment,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY segment
        ORDER BY total_sales DESC;
        """)

    elif "monthly sales" in question:
        return run_query("""
        SELECT
            strftime('%Y-%m', order_date) AS month,
            SUM(sales) AS total_sales
        FROM sales
        GROUP BY month
        ORDER BY month;
        """)

    else:
        return "Sorry, I don't understand that question yet."

In [101]:
simple_copilot("show me monthly sales")

      month  total_sales
0   2023-01   14518.0550
1   2023-02    4519.8920
2   2023-03   56933.9090
3   2023-04   28295.3450
4   2023-05   26319.7670
5   2023-06   34669.4796
6   2023-07   33946.3930
7   2023-08   28918.3385
8   2023-09   82670.4288
9   2023-10   32413.3390
10  2023-11   78826.9567
11  2023-12   72008.3085
12  2024-01   18461.9156
13  2024-02   11951.4110
14  2024-03   39978.6280
15  2024-04   34195.2085
16  2024-05   30246.9465
17  2024-06   24797.2920
18  2024-07   28765.3250
19  2024-08   37057.0042
20  2024-09   64627.0460
21  2024-10   31407.1335
22  2024-11   75972.5635
23  2024-12   75532.5572
24  2025-01   18830.3310
25  2025-02   22978.8150
26  2025-03   53031.0690
27  2025-04   38829.1590
28  2025-05   57042.8380
29  2025-06   40937.1480
30  2025-07   40300.4990
31  2025-08   31716.8143
32  2025-09   73521.6629
33  2025-10   59831.0010
34  2025-11   79411.9658
35  2025-12   97502.2770
36  2026-01   44259.2140
37  2026-02   20301.1334
38  2026-03   60728.4808
39  2026-04   36779.0361
40  2026-05   45155.4822
41  2026-06   53056.0777
42  2026-07   45989.4960
43  2026-08   64129.7580
44  2026-09   88064.5320
45  2026-10   83474.7832
46  2026-11  118454.5050
47  2026-12   85175.0328

In [102]:
run_query("""
PRAGMA table_info(sales);
""")

    cid            name       type  notnull dflt_value  pk
0     0          row_id    INTEGER        0       None   0
1     1        order_id       TEXT        0       None   0
2     2      order_date  TIMESTAMP        0       None   0
3     3       ship_date  TIMESTAMP        0       None   0
4     4       ship_mode       TEXT        0       None   0
5     5     customer_id       TEXT        0       None   0
6     6   customer_name       TEXT        0       None   0
7     7         segment       TEXT        0       None   0
8     8  country_region       TEXT        0       None   0
9     9            city       TEXT        0       None   0
10   10  state_province       TEXT        0       None   0
11   11     postal_code       TEXT        0       None   0
12   12          region       TEXT        0       None   0
13   13      product_id       TEXT        0       None   0
14   14        category       TEXT        0       None   0
15   15    sub_category       TEXT        0       None   0
16   16    product_name       TEXT        0       None   0
17   17           sales       REAL        0       None   0
18   18        quantity    INTEGER        0       None   0
19   19        discount       REAL        0       None   0
20   20          profit       REAL        0       None   0

In [103]:
schema = """
Table: sales

Columns:
row_id INTEGER
order_id TEXT
order_date TIMESTAMP
ship_date TIMESTAMP
ship_mode TEXT
customer_id TEXT
customer_name TEXT
segment TEXT
country_region TEXT
city TEXT
state_province TEXT
postal_code TEXT
region TEXT
product_id TEXT
category TEXT
sub_category TEXT
product_name TEXT
sales REAL
quantity INTEGER
discount REAL
profit REAL
"""

In [104]:
system_prompt = f"""
You are a Business Intelligence SQL assistant.

Your job is to convert business questions into SQLite SQL queries.

Use only the following database schema:

{schema}

Rules:
1. Use only the sales table.
2. Generate valid SQLite SQL.
3. Do not invent columns.
4. Return only the SQL query.
5. Use SUM(sales) for total sales.
6. Use SUM(profit) for total profit.
7. Use GROUP BY when comparing categories, regions, customers, or products.
"""

In [105]:
%pip install openai

Requirement already satisfied: openai in /opt/anaconda3/lib/python3.13/site-packages (3.6.0)
Requirement already satisfied: anyio<5,>=4.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.10.0)
Requirement already satisfied: httpx2<3,>=2.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (2.12.0)
Requirement already satisfied: jiter<1,>=0.16.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (0.16.0)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (2.12.4)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.13/site-packages (from openai) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.13/site-packages (from anyio<5,>=4.10.0->openai) (3.19)
Requirement already satisfied: httpcore2==2.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from httpx2<3,>=2.7.0->openai) (2.12.0)
Requirement already satisfied: truststore>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from httpx2<3,>=2.7.0->openai) (0.10.1)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore2==2.12.0->httpx2<3,>=2.7.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai) (0.4.2)
Note: you may need to restart the kernel to use updated packages.

In [106]:
%pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.13/site-packages (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [109]:
from pathlib import Path

env_path = Path("../.env").resolve()

print("Path:", env_path)
print("Exists:", env_path.exists())

if env_path.exists():
    print("File size:", env_path.stat().st_size)

Path: /Users/thanishkareddy/Desktop/AI-Business-Intelligence-Copilot/.env
Exists: True
File size: 180

In [114]:
import os
from dotenv import load_dotenv

os.environ.pop("OPENAI_API_KEY", None)

load_dotenv("../.env", override=True)

print("API key found" if os.getenv("OPENAI_API_KEY") else "API key not found")

API key found

In [116]:
import openai

print(openai.__version__)

3.6.0

In [118]:
import httpx2

print(httpx2.__version__)

2.12.0

In [1]:
%pip install httpx2==2.7.0

Requirement already satisfied: httpx2==2.7.0 in /opt/anaconda3/lib/python3.13/site-packages (2.7.0)
Requirement already satisfied: anyio>=4.10 in /opt/anaconda3/lib/python3.13/site-packages (from httpx2==2.7.0) (4.10.0)
Requirement already satisfied: httpcore2==2.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from httpx2==2.7.0) (2.7.0)
Requirement already satisfied: idna>=3.18 in /opt/anaconda3/lib/python3.13/site-packages (from httpx2==2.7.0) (3.19)
Requirement already satisfied: truststore>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from httpx2==2.7.0) (0.10.1)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore2==2.7.0->httpx2==2.7.0) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio>=4.10->httpx2==2.7.0) (1.3.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
from dotenv import load_dotenv
from openai import OpenAI
import httpx2

load_dotenv("../.env", override=True)

print("API key found" if os.getenv("OPENAI_API_KEY") else "API key not found")
print("httpx2 version:", httpx2.__version__)

API key found
httpx2 version: 2.7.0

In [5]:
from openai import OpenAI

client = OpenAI()

response = client.responses.create(
    model="gpt-5.6-luna",
    input="Reply with only: AI connection working"
)

print(response.output_text)

AI connection working

In [7]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../data/superstore.db")

print("Database connected")

Database connected

In [9]:
schema = """
Table: sales

Columns:
row_id INTEGER
order_id TEXT
order_date TIMESTAMP
ship_date TIMESTAMP
ship_mode TEXT
customer_id TEXT
customer_name TEXT
segment TEXT
country_region TEXT
city TEXT
state_province TEXT
postal_code TEXT
region TEXT
product_id TEXT
category TEXT
sub_category TEXT
product_name TEXT
sales REAL
quantity INTEGER
discount REAL
profit REAL
"""

In [11]:
system_prompt = f"""
You are a Business Intelligence SQL assistant.

Your job is to convert business questions into SQLite SQL queries.

Use only this database schema:

{schema}

Rules:
1. Use only the sales table.
2. Generate valid SQLite SQL.
3. Do not invent columns.
4. Return only the SQL query.
5. Use SUM(sales) for total sales.
6. Use SUM(profit) for total profit.
7. Use GROUP BY when comparing regions, categories, customers, products, or segments.
"""

In [13]:
def generate_sql(question):
    response = client.responses.create(
        model="gpt-5.6-luna",
        instructions=system_prompt,
        input=question
    )

    return response.output_text

In [15]:
generate_sql("Which region has the highest sales?")

'SELECT region, SUM(sales) AS total_sales\nFROM sales\nGROUP BY region\nORDER BY total_sales DESC\nLIMIT 1;'

In [43]:
def execute_sql(sql):
    sql_clean = sql.strip().lower()

    if not sql_clean.startswith("select"):
        raise ValueError("Only SELECT queries are allowed.")

    return pd.read_sql_query(sql, conn)

In [35]:
question = "Which region has the highest sales?"

sql = generate_sql(question)

print("Generated SQL:")
print(sql)

result = execute_sql(sql)

result

Generated SQL:
SELECT region, SUM(sales) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC
LIMIT 1;

  region  total_sales
0   West  739813.6085

In [36]:
def ai_copilot(question):
    sql = generate_sql(question)
    result = execute_sql(sql)

    print("Question:")
    print(question)

    print("\nGenerated SQL:")
    print(sql)

    print("\nResult:")
    return result

In [37]:
ai_copilot("Which category has the highest profit?")

Question:
Which category has the highest profit?

Generated SQL:
SELECT category, SUM(profit) AS total_profit
FROM sales
GROUP BY category
ORDER BY total_profit DESC
LIMIT 1;

Result:

     category  total_profit
0  Technology   146543.3756

In [38]:
def explain_result(question, result):
    result_text = result.to_string(index=False)

    response = client.responses.create(
        model="gpt-5.6-luna",
        input=f"""
You are a Business Intelligence analyst.

Business question:
{question}

Query result:
{result_text}

Explain the result in 2-3 clear business sentences.
Use only the numbers shown in the query result.
Do not invent any additional facts.
"""
    )

    return response.output_text

In [39]:
question = "Which category has the highest profit?"

sql = generate_sql(question)
result = execute_sql(sql)

explanation = explain_result(question, result)

print(explanation)

Technology has the highest profit, totaling **146,543.3756**. This indicates that Technology is the top-performing category by profit in the query results.

In [47]:
def business_intelligence_copilot(question):
    try:
        sql = generate_sql(question)
        result = execute_sql(sql)
        explanation = explain_result(question, result)

        print("QUESTION:")
        print(question)

        print("\nGENERATED SQL:")
        print(sql)

        print("\nRESULT:")
        display(result)

        print("\nBUSINESS EXPLANATION:")
        print(explanation)

    except Exception as e:
        print("Sorry, I could not answer that question.")
        print("Error:", e)

In [48]:
business_intelligence_copilot(
    "Which region has the lowest profit margin?"
)

QUESTION:
Which region has the lowest profit margin?

GENERATED SQL:
SELECT
  region,
  SUM(profit) / NULLIF(SUM(sales), 0) AS profit_margin
FROM sales
GROUP BY region
ORDER BY profit_margin ASC
LIMIT 1;

RESULT:

    region  profit_margin
0  Central       0.079228

BUSINESS EXPLANATION:
The Central region has the lowest profit margin at 0.079228. This indicates that Central generates the smallest profit relative to its sales among the regions shown.

In [49]:
business_intelligence_copilot(
    "What are the top 5 products by sales?"
)

QUESTION:
What are the top 5 products by sales?

GENERATED SQL:
SELECT
    product_name,
    SUM(sales) AS total_sales
FROM sales
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 5;

RESULT:

                                        product_name  total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

BUSINESS EXPLANATION:
The Canon imageCLASS 2200 Advanced Copier leads the top five products with total sales of 61599.824. It is followed by the Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind at 27453.384, the Cisco TelePresence System EX90 Videoconferencing Unit at 22638.480, the HON 5400 Series Task Chairs for Big and Tall at 21870.576, and the GBC DocuBind TL300 Electric Binding System at 19823.479.

In [51]:
business_intelligence_copilot(
    "Which customer has the highest total sales?"
)

QUESTION:
Which customer has the highest total sales?

GENERATED SQL:
SELECT
    customer_id,
    customer_name,
    SUM(sales) AS total_sales
FROM sales
GROUP BY customer_id, customer_name
ORDER BY total_sales DESC
LIMIT 1;

RESULT:

  customer_id customer_name  total_sales
0    SM-20320   Sean Miller     25043.05

BUSINESS EXPLANATION:
Sean Miller (customer ID SM-20320) has the highest total sales, totaling $25,043.05.

In [53]:
def generate_executive_summary():
    summary_query = """
    SELECT
        SUM(sales) AS total_sales,
        SUM(profit) AS total_profit,
        (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent,
        COUNT(DISTINCT order_id) AS total_orders,
        COUNT(DISTINCT customer_id) AS total_customers
    FROM sales;
    """

    summary_data = execute_sql(summary_query)

    return summary_data

In [55]:
generate_executive_summary()

,total_sales,total_profit,profit_margin_percent,total_orders,total_customers
0,2.326534e+06,292296.8146,12.563615,5111,804

In [57]:
def ai_executive_summary():
    kpis = generate_executive_summary()

    kpi_text = kpis.to_string(index=False)

    response = client.responses.create(
        model="gpt-5.6-luna",
        input=f"""
You are a Business Intelligence analyst.

Here are the company's key performance indicators:

{kpi_text}

Write a concise executive summary in 3-4 sentences.

Rules:
1. Mention total sales, total profit, profit margin, total orders, and total customers.
2. Use clear business language.
3. Do not invent any information.
4. Only use the data provided.
"""
    )

    return response.output_text

In [59]:
ai_executive_summary()

'The business generated total sales of $2,326,534.35 and total profit of $292,296.81. The profit margin was 12.56%. It processed 5,111 total orders and served 804 total customers.'

In [61]:
def get_region_summary():
    query = """
    SELECT
        region,
        SUM(sales) AS total_sales,
        SUM(profit) AS total_profit,
        (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
    FROM sales
    GROUP BY region
    ORDER BY total_sales DESC;
    """

    return execute_sql(query)

In [63]:
get_region_summary()

    region  total_sales  total_profit  profit_margin_percent
0     West  739813.6085   110798.8170              14.976585
1     East  691828.1680    94883.2603              13.714859
2  Central  503170.6728    39865.3070               7.922820
3    South  391721.9050    46749.4303              11.934342

In [65]:
def get_category_summary():
    query = """
    SELECT
        category,
        SUM(sales) AS total_sales,
        SUM(profit) AS total_profit,
        (SUM(profit) / SUM(sales)) * 100 AS profit_margin_percent
    FROM sales
    GROUP BY category
    ORDER BY total_sales DESC;
    """

    return execute_sql(query)

In [67]:
get_category_summary()

          category  total_sales  total_profit  profit_margin_percent
0       Technology  839893.2790   146543.3756              17.447857
1        Furniture  754747.7613    19729.9956               2.614118
2  Office Supplies  731893.3140   126023.4434              17.218827

In [69]:
def advanced_executive_summary():
    kpis = generate_executive_summary()
    regions = get_region_summary()
    categories = get_category_summary()

    response = client.responses.create(
        model="gpt-5.6-luna",
        input=f"""
You are a Business Intelligence analyst.

Overall KPIs:
{kpis.to_string(index=False)}

Regional Performance:
{regions.to_string(index=False)}

Category Performance:
{categories.to_string(index=False)}

Write a concise executive summary in 5-6 sentences.

Include:
1. Overall sales, profit, and profit margin.
2. Strongest region.
3. Weakest region based on profit margin.
4. Strongest product category.
5. Weakest product category based on profit margin.
6. One clear business takeaway.

Do not invent any data.
Use only the information provided.
"""
    )

    return response.output_text

In [71]:
advanced_executive_summary()

'Overall sales were $2.33 million, with total profit of $292,296.81 and a profit margin of 12.56%. The West was the strongest region, generating $739,813.61 in sales and $110,798.82 in profit. Central was the weakest region based on profit margin, at 7.92%. Technology was the strongest product category, with $839,893.28 in sales, $146,543.38 in profit, and a 17.45% margin. Furniture was the weakest category by profit margin, at 2.61%, indicating that improving Furniture profitability and Central-region performance should be key business priorities.'

In [73]:
def get_monthly_summary():
    query = """
    SELECT
        strftime('%Y-%m', order_date) AS month,
        SUM(sales) AS total_sales,
        SUM(profit) AS total_profit
    FROM sales
    GROUP BY month
    ORDER BY month;
    """

    return execute_sql(query)

In [75]:
get_monthly_summary()

      month  total_sales  total_profit
0   2023-01   14518.0550     2539.3907
1   2023-02    4519.8920      862.3084
2   2023-03   56933.9090      693.4499
3   2023-04   28295.3450     3488.8352
4   2023-05   26319.7670     3196.3918
5   2023-06   34669.4796     4999.7594
6   2023-07   33946.3930     -841.4826
7   2023-08   28918.3385     5765.2250
8   2023-09   82670.4288     8593.6302
9   2023-10   32413.3390     3469.1749
10  2023-11   78826.9567     9362.9557
11  2023-12   72008.3085     9554.6571
12  2024-01   18461.9156    -3189.8030
13  2024-02   11951.4110     2813.8508
14  2024-03   39978.6280     9930.6134
15  2024-04   34195.2085     4187.4962
16  2024-05   30246.9465     4677.1370
17  2024-06   24797.2920     3335.5572
18  2024-07   28765.3250     3288.6483
19  2024-08   37057.0042     5371.6274
20  2024-09   64627.0460     8220.0251
21  2024-10   31407.1335     2817.9660
22  2024-11   75972.5635    12474.7884
23  2024-12   75532.5572     8093.0627
24  2025-01   18830.3310     2916.0233
25  2025-02   22978.8150     5004.5795
26  2025-03   53031.0690     3707.8862
27  2025-04   38829.1590     2991.6609
28  2025-05   57042.8380     8676.6964
29  2025-06   40937.1480     4926.3194
30  2025-07   40300.4990     4559.8827
31  2025-08   31716.8143     2317.4993
32  2025-09   73521.6629     9370.1031
33  2025-10   59831.0010    16256.8422
34  2025-11   79411.9658     4011.4075
35  2025-12   97502.2770    17926.3013
36  2026-01   44259.2140     7231.6391
37  2026-02   20301.1334     1613.8720
38  2026-03   60728.4808    15013.0910
39  2026-04   36779.0361      957.5300
40  2026-05   45155.4822     6299.8072
41  2026-06   53056.0777     8246.5707
42  2026-07   45989.4960     7006.5012
43  2026-08   64129.7580     9488.0722
44  2026-09   88064.5320    11050.8024
45  2026-10   83474.7832    10670.5312
46  2026-11  118454.5050     9692.1037
47  2026-12   85175.0328     8655.8269

In [77]:
def get_yearly_summary():
    query = """
    SELECT
        strftime('%Y', order_date) AS year,
        SUM(sales) AS total_sales,
        SUM(profit) AS total_profit
    FROM sales
    GROUP BY year
    ORDER BY year;
    """

    return execute_sql(query)

In [79]:
get_yearly_summary()

   year  total_sales  total_profit
0  2023  494040.2121    51684.2957
1  2024  472993.0310    62020.9695
2  2025  613933.5800    82665.2018
3  2026  745567.5312    95926.3476

In [81]:
yearly_summary = get_yearly_summary()

yearly_summary["sales_growth_percent"] = (
    yearly_summary["total_sales"].pct_change() * 100
)

yearly_summary["profit_growth_percent"] = (
    yearly_summary["total_profit"].pct_change() * 100
)

yearly_summary

,year,total_sales,total_profit,sales_growth_percent,profit_growth_percent
0,2023,494040.2121,51684.2957,NaN,NaN
1,2024,472993.0310,62020.9695,-4.260216,19.999641
2,2025,613933.5800,82665.2018,29.797595,33.285891
3,2026,745567.5312,95926.3476,21.441074,16.041993

In [83]:
def get_yearly_growth():
    yearly = get_yearly_summary()

    yearly["sales_growth_percent"] = (
        yearly["total_sales"].pct_change() * 100
    )

    yearly["profit_growth_percent"] = (
        yearly["total_profit"].pct_change() * 100
    )

    return yearly

In [85]:
get_yearly_growth()

,year,total_sales,total_profit,sales_growth_percent,profit_growth_percent
0,2023,494040.2121,51684.2957,NaN,NaN
1,2024,472993.0310,62020.9695,-4.260216,19.999641
2,2025,613933.5800,82665.2018,29.797595,33.285891
3,2026,745567.5312,95926.3476,21.441074,16.041993

In [87]:
def final_executive_summary():
    kpis = generate_executive_summary()
    regions = get_region_summary()
    categories = get_category_summary()
    yearly_growth = get_yearly_growth()

    response = client.responses.create(
        model="gpt-5.6-luna",
        input=f"""
You are a Business Intelligence analyst.

Overall KPIs:
{kpis.to_string(index=False)}

Regional Performance:
{regions.to_string(index=False)}

Category Performance:
{categories.to_string(index=False)}

Yearly Performance and Growth:
{yearly_growth.to_string(index=False)}

Write a professional executive summary in 6-8 sentences.

Include:
1. Overall sales, profit, and profit margin.
2. Latest-year sales growth.
3. Latest-year profit growth.
4. Strongest region.
5. Weakest region based on profit margin.
6. Strongest product category.
7. Weakest product category based on profit margin.
8. One clear business recommendation.

Do not invent data.
Use only the information provided.
"""
    )

    return response.output_text

In [89]:
final_executive_summary()

'Overall, the business generated **$2.33 million in sales**, **$292,296.81 in profit**, and an overall **profit margin of 12.56%**. In the latest year, 2026, sales increased **21.44%**, while profit grew **16.04%**. The **West** was the strongest region, recording **$739,813.61 in sales**, **$110,798.82 in profit**, and a **14.98% margin**. The **Central** region was the weakest based on profit margin, at **7.92%**. **Technology** was the strongest product category, delivering **$146,543.38 in profit** and the highest category margin at **17.45%**. **Furniture** was the weakest category based on profit margin, with a margin of only **2.61%**. Management should prioritize improving Furniture profitability and Central-region performance while continuing to support the higher-margin Technology category and strong West-region operations.'

In [90]:
%pip install streamlit plotly

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.13/site-packages (1.51.0)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.13/site-packages (6.3.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (4.15.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in /opt/anaconda3/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.